name: Checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  fmt:
    name: Format
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - run: cargo fmt --all -- --check

  clippy:
    name: Lint
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - run: cargo clippy
