name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: cargo fmt
        run: cargo fmt --all -- --check
