name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Format
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: cargo fmt
        run: cargo fmt --all -- --check
