name: Test Suite

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      AURORA_PLUS_API_KEY: ${{secrets.AURORA_PLUS_API_KEY}}
      RPC_URL: ${{secrets.RPC_URL}}
      NETWORK_NAME: ${{secrets.NETWORK_NAME}}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
    steps:
      # - name: Adding repo directory
      #   run: |
      #     /usr/bin/git config --global --add safe.directory /root/privileged_runners_workdir/runners/Aurora-Priv-GH-runner-2/aurora-api-testing-rs/aurora-api-testing-rs/relayer-test-data-generator
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Clone DB repository
        uses: actions/checkout@v4
        with:
          repository: aurora-is-near/relayer-test-data-generator
          ssh-key: ${{ secrets.SSH_RELAYER_TEST_DATA_GENERATOR }}
          path: relayer-test-data-generator
          ref: main

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install junit-report
        run: |
          cargo install cargo2junit

      - name: build
        run: |
          cargo build

      - name: Run tests
        continue-on-error: true
        run: |
          cp .env.example .env
          source .env
          export AURORA_PLUS_API_KEY=${{secrets.AURORA_PLUS_API_KEY}}
          RUSTC_BOOTSTRAP=1 cargo test -- -Z unstable-options --format json --report-time 2> test.log | tee results.json
          cat results.json | cargo2junit > results.xml
          cat test.log

      - name: Upload results
        run: |
          npm install --save-dev @datadog/datadog-ci
          DD_ENV=ci DATADOG_SITE=datadoghq.eu npx datadog-ci junit upload --service "aurora-relayer-api-dynamic-tests-aurora-plus-mainnet-rs" results.xml
