name: Aurora API Testing

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: self-hosted
    env:
      AURORA_PLUS_API_KEY: ${{secrets.AURORA_PLUS_API_KEY}}
      RPC_URL: ${{secrets.RPC_URL}}
      NETWORK_NAME: ${{secrets.NETWORK_NAME}}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
    steps:
      - name: Adding repo directory
        run: |
          /usr/bin/git config --global --add safe.directory /root/privileged_runners_workdir/runners/Aurora-Priv-GH-runner-2/aurora-api-testing-rs/aurora-api-testing-rs/relayer-test-data-generator

      - name: Clone DB repository
        uses: actions/checkout@v3
        with:
          repository: aurora-is-near/relayer-test-data-generator
          ssh-key: ${{ secrets.SSH_RELAYER_TEST_DATA_GENERATOR }}
          path: relayer-test-data-generator
          ref: main

      - name: rust update
        run: |
          rustup uninstall 1.67.0
          rustup default nightly
          rustc --version
          rustup show

      - name: Install junit-report
        run: |
          cargo install cargo2junit

      - name: build
        run: |
          cargo build

      - name: Run tests & upload results
        run: |
          cp .env.example .env
          source .env
          export AURORA_PLUS_API_KEY=${{secrets.AURORA_PLUS_API_KEY}}
          cargo test --no-fail-fast -- -Z unstable-options --format json --report-time | cargo2junit > results.xml
          npm install --save-dev @datadog/datadog-ci
          DD_ENV=ci DATADOG_SITE=datadoghq.eu npx datadog-ci junit upload --service "aurora-relayer-api-dynamic-tests-aurora-plus-mainnet-rs" results.xml
