name: aurora api dynamic testing - tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{secrets.API_KEY}}
      CHAIN_ID: ${{secrets.CHAIN_ID}}
      RPC_URL: ${{secrets.RPC_URL}}
      NETWORK_NAME: ${{secrets.NETWORK_NAME}}
      DB_FILE_PATH: ${{secrets.DB_FILE_PATH}}
      RUNS_TABLE: ${{secrets.RUNS_TABLE}}
      TASKS_TABLE: ${{secrets.TASKS_TABLE}}
      DATA_TABLE: ${{secrets.DATA_TABLE}}
      RUNS_X_TASKS_TABLE: ${{secrets.RUNS_X_TASKS_TABLE}}
      TASKS_X_DATA_TABLE: ${{secrets.TASKS_X_DATA_TABLE}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: cargo test
        run: cp .env.example .env && cargo test --all --all-features
