name: aurora api dynamic testing - tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      AURORA_PLUS_API_KEY: ${{secrets.AURORA_PLUS_API_KEY}}
      RPC_URL: ${{secrets.RPC_URL}}
      NETWORK_NAME: ${{secrets.NETWORK_NAME}}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Clone DB repository
        uses: actions/checkout@v3
        with:
          repository: aurora-is-near/relayer-test-data-generator
          ssh-key: ${{ secrets.SSH_RELAYER_TEST_DATA_GENERATOR }}
          path: relayer-test-data-generator
          ref: main
      - name: Install Datadog-ci
        run: |
          cd go-ethereum/dynamic
          npm install --save-dev @datadog/datadog-ci
      - name: Install rust-junit-report
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: cargo test
        run: cp .env.example .env ; source .env; export AURORA_PLUS_API_KEY=${{secrets.AURORA_PLUS_API_KEY}}; cargo test --all --all-features